// <auto-generated /> (手写版——等 Source Generator 工作后替换)
using ShootingGame.Shared.Protocol;

namespace ShootingGame.Shared.ECS
{
    public partial struct HealthComponent
    {
        public const byte ComponentTypeId = 1;

        private byte __last_Current;
        public bool HasDelta_Current => Current != __last_Current;
        public bool HasAnyDelta => HasDelta_Current;

        public void WriteDelta(PacketWriter w)
        {
            w.WriteByte(ComponentTypeId);
            byte mask = 0;
            if (HasDelta_Current) mask |= 1;
            w.WriteByte(mask);
            if (HasDelta_Current) w.WriteByte(Current);
        }
        public void ReadDelta(PacketReader r)
        {
            r.ReadByte(); // componentTypeId
            byte mask = r.ReadByte();
            if ((mask & 1) != 0) Current = r.ReadByte();
        }
        public void WriteFull(PacketWriter w)
        {
            w.WriteByte(ComponentTypeId);
            w.WriteByte(Current);
        }
        public void ReadFull(PacketReader r)
        {
            r.ReadByte(); // componentTypeId
            Current = r.ReadByte();
            MarkClean();
        }
        public void MarkClean() { __last_Current = Current; }
    }
}
