// <auto-generated /> (手写版)
using ShootingGame.Shared.Math;
using ShootingGame.Shared.Protocol;

namespace ShootingGame.Shared.ECS
{
    public partial struct MovementComponent
    {
        public const byte ComponentTypeId = 2;

        private Vec3 __last_Velocity;
        private float __last_VerticalVelocity;
        private bool __last_IsGrounded;

        public bool HasDelta_Velocity => Velocity != __last_Velocity;
        public bool HasDelta_VerticalVelocity => VerticalVelocity != __last_VerticalVelocity;
        public bool HasDelta_IsGrounded => IsGrounded != __last_IsGrounded;
        public bool HasAnyDelta => HasDelta_Velocity || HasDelta_VerticalVelocity || HasDelta_IsGrounded;

        public void WriteDelta(PacketWriter w)
        {
            w.WriteByte(ComponentTypeId);
            byte mask = 0;
            if (HasDelta_Velocity) mask |= 1;
            if (HasDelta_VerticalVelocity) mask |= 2;
            if (HasDelta_IsGrounded) mask |= 4;
            w.WriteByte(mask);
            if (HasDelta_Velocity) w.WriteVec3(Velocity);
            if (HasDelta_VerticalVelocity) w.WriteFloat(VerticalVelocity);
            if (HasDelta_IsGrounded) w.WriteBool(IsGrounded);
        }
        public void ReadDelta(PacketReader r)
        {
            r.ReadByte();
            byte mask = r.ReadByte();
            if ((mask & 1) != 0) Velocity = r.ReadVec3();
            if ((mask & 2) != 0) VerticalVelocity = r.ReadFloat();
            if ((mask & 4) != 0) IsGrounded = r.ReadBool();
        }
        public void WriteFull(PacketWriter w)
        {
            w.WriteByte(ComponentTypeId);
            w.WriteVec3(Velocity);
            w.WriteFloat(VerticalVelocity);
            w.WriteBool(IsGrounded);
        }
        public void ReadFull(PacketReader r)
        {
            r.ReadByte();
            Velocity = r.ReadVec3();
            VerticalVelocity = r.ReadFloat();
            IsGrounded = r.ReadBool();
            MarkClean();
        }
        public void MarkClean()
        {
            __last_Velocity = Velocity;
            __last_VerticalVelocity = VerticalVelocity;
            __last_IsGrounded = IsGrounded;
        }
    }
}
