// <auto-generated /> (手写版)
using ShootingGame.Shared.Math;
using ShootingGame.Shared.Protocol;

namespace ShootingGame.Shared.ECS
{
    public partial struct TransformComponent
    {
        public const byte ComponentTypeId = 3;

        private Vec3 __last_Position;
        private Quat __last_Rotation;

        public bool HasDelta_Position => Position != __last_Position;
        public bool HasDelta_Rotation => Rotation != __last_Rotation;
        public bool HasAnyDelta => HasDelta_Position || HasDelta_Rotation;

        public void WriteDelta(PacketWriter w)
        {
            w.WriteByte(ComponentTypeId);
            byte mask = 0;
            if (HasDelta_Position) mask |= 1;
            if (HasDelta_Rotation) mask |= 2;
            w.WriteByte(mask);
            if (HasDelta_Position) w.WriteVec3(Position);
            if (HasDelta_Rotation) w.WriteQuat(Rotation);
        }
        public void ReadDelta(PacketReader r)
        {
            r.ReadByte();
            byte mask = r.ReadByte();
            if ((mask & 1) != 0) Position = r.ReadVec3();
            if ((mask & 2) != 0) Rotation = r.ReadQuat();
        }
        public void WriteFull(PacketWriter w)
        {
            w.WriteByte(ComponentTypeId);
            w.WriteVec3(Position);
            w.WriteQuat(Rotation);
        }
        public void ReadFull(PacketReader r)
        {
            r.ReadByte();
            Position = r.ReadVec3();
            Rotation = r.ReadQuat();
            MarkClean();
        }
        public void MarkClean()
        {
            __last_Position = Position;
            __last_Rotation = Rotation;
        }
    }
}
