using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading;
using ShootingGame.Network;
using ShootingGame.Shared.Math;
using ShootingGame.Shared.Protocol;
using ShootingGame.Shared.Simulation;
using ShootingGame.Shared.Physics;
using ShootingGame.Shared.ECS;
using ShootingGame.Shared.Ability;
using ShootingGame.Shared.Hero;
using ShootingGame.Shared.GameplayTags;
using ShootingGame.Server.ECS;

namespace ShootingGame.Server
{
    /// <summary>
    /// BattleRoom manages a single battle instance.
    /// Handles BattleReady -> BattleStart handshake, frame loop, and battle lifecycle.
    /// </summary>
    public class BattleRoom
    {
        public BattleContext Context { get; }
        private readonly MatchMaker _matchMaker;
        private readonly object _lock = new object();

        // Battle state
        private int _frameId;
        private volatile bool _isRunning;
        private volatile bool _hasStarted;
        private volatile bool _hasEnded;

        // Player readiness
        private readonly Dictionary<int, string> _playerEndpoints = new Dictionary<int, string>();
        private readonly List<ServerSnapshotProducedMessage> _snapshotMessages = new List<ServerSnapshotProducedMessage>();

        // Player state
        // Player membership only. Authoritative runtime state lives on ECS entities.
        private readonly HashSet<int> _playerIds = new HashSet<int>();

        // Bullet system: projectile state is owned by ECS entities.
        private readonly List<HitEventMsg> _pendingHitEvents = new List<HitEventMsg>();
        private readonly List<DamageAppliedEvent> _damageEvents = new List<DamageAppliedEvent>();

        // Frame history for retransmission
        private readonly Dictionary<int, AllPlayerOperation> _frameHistory = new Dictionary<int, AllPlayerOperation>();
        private const int MaxFrameHistory = 64;

        // Game state
        private int _killerTeamId;
        private int _killerPlayerId;

        // 死斗(FFA)模式状态
        private bool IsDeathmatch => Context.Mode == 1;
        private readonly Random _spawnRng = new Random();

        // Respawn system
        private List<SpawnPoint> _team1SpawnPoints;
        private List<SpawnPoint> _team2SpawnPoints;
        private List<SpawnPoint> _anySpawnPoints;
        private List<SpawnPoint> _deathmatchSpawnPoints;
        private readonly Dictionary<int, int> _lastDeathmatchSpawnIndex = new Dictionary<int, int>();

        // GameOver reliable retransmission
        private int _gameOverRetransmitRemaining;
        private const int GameOverRetransmitTicks = 60; // ~1 second at 60fps

        // RTT provider from UDP server
        private Func<int, float> _getPlayerRtt; // returns RTT in seconds

        // Pending ability confirmations (generated by server, sent back to client)
        private readonly List<AbilityEventData> _pendingAbilityConfirmations = new List<AbilityEventData>();

        // Input receive rate logging

        // Collision world
        private CollisionWorld _collisionWorld;

        // ECS world
        private ServerECSWorld _ecsWorld;
        private Thread _frameThread;

        // Frame timing
        private readonly float _frameInterval = GameConstants.TickDelta;
        private const int MaxCatchupFrames = 5;

        // Default fallback spawn positions (when no spawn points are configured)
        private static readonly Vec3[] DefaultSpawnPositions = new Vec3[]
        {
            new Vec3(0, 0, 0),
            new Vec3(5, 0, 5),
            new Vec3(-5, 0, 5),
            new Vec3(0, 0, -5),
            new Vec3(5, 0, -5),
            new Vec3(-5, 0, -5),
            new Vec3(10, 0, 0),
            new Vec3(-10, 0, 0),
            new Vec3(0, 0, 10),
            new Vec3(0, 0, -10)
        };

        public int BattleId => Context.BattleId;
        public bool IsStarted => _hasStarted;

        /// <summary>强制开始（跳过 BattleReady 握手，用于英雄确认后直接开始）</summary>
        public void ForceStart()
        {
            lock (_lock)
            {
                if (!_hasStarted)
                {
                    _hasStarted = true;
                    // Use the ECS-owned player connection state.
                    foreach (var player in Context.Players)
                    {
                        int bpId = Context.GetBattlePlayerId(player.UserId);
                        _ecsWorld.SetPlayerReady(bpId, true);
                    }

                    // 完整启动：广播 BattleStart + 启动帧循环
                    BroadcastBattleStart();
                    StartFrameLoop();
                    Console.WriteLine($"[BattleRoom] ForceStart: battle {BattleId} started, frame loop launched");
                }
            }
        }

        /// <summary>
        /// Set the RTT provider callback so the room can use per-player RTT.
        /// </summary>
        public void SetRttProvider(Func<int, float> getRtt)
        {
            _getPlayerRtt = getRtt;
        }

        public BattleRoom(BattleContext context, MatchMaker matchMaker)
        {
            Context = context;
            _matchMaker = matchMaker;

            RegisterAbilityRpcHandlers();
            InitializeBattle();
        }

        public void ApplyHeroSelection(int userId)
        {
            lock (_lock)
            {
                if (_hasStarted || _ecsWorld == null) return;

                var player = Context.Players.Find(value => value.UserId == userId);
                if (player == null) return;

                int bpId = Context.GetBattlePlayerId(userId);
                if (!_ecsWorld.TryBuildCurrentSnapshot(bpId, 0, out var snapshot)) return;

                var heroConfig = HeroRegistry.GetHero(player.HeroId)
                    ?? HeroRegistry.GetHero(HeroRegistry.DefaultHeroId);
                _ecsWorld.RegisterPlayer(bpId, snapshot, heroConfig);
                _ecsWorld.SetPlayerTeam(bpId, player.TeamId);
                Log($"Applied hero selection before start: user={userId}, bp={bpId}, hero={heroConfig?.HeroId}");
            }
        }

        /// <summary>
        /// 技能预测确认链（RPC 版）：客户端预测施法 → [ServerRpc] RequestActivateAbility
        /// → 服务器验证 + 激活 AbilityLifecycleSystem → 回程 Confirm/Reject（[ClientRpc] 语义）。
        /// 特效由客户端程序化生成，Confirm 保留 / Reject 回滚。
        /// </summary>
        private void RegisterAbilityRpcHandlers()
        {
            RegisterRpcHandler("global::PlayerCombatBehaviour", "RequestActivateAbility",
                new[] { "System.Int32", "System.Int32" }, (bpId, r) =>
            {
                int assetId = r.ReadInt32();
                int predictedId = r.ReadInt32();
                if (!_hasStarted || _hasEnded)
                    return;
                if (_ecsWorld.IsPlayerDisconnected(bpId))
                    return;

                // 服务器权威验证 + 激活（复用现有 AbilityLifecycleSystem）
                ushort instanceId = _ecsWorld.TryActivateAbility(bpId, (byte)assetId);
                if (instanceId > 0)
                {
                    // ConfirmAbility(predictedId, instanceId)：客户端用 predictedId 匹配预测特效
                    SendClientRpc(bpId,
                        RpcMethodHash.Compute("global::PlayerCombatBehaviour.ConfirmAbility(System.Int32,System.Int32)"),
                        predictedId, instanceId);
                    Console.WriteLine($"[RPC] Skill: bp{bpId} assetId={assetId} pred={predictedId} -> Confirm instance={instanceId}");
                }
                else
                {
                    // RejectAbility(predictedId)：客户端回滚预测特效
                    SendClientRpc(bpId,
                        RpcMethodHash.Compute("global::PlayerCombatBehaviour.RejectAbility(System.Int32)"),
                        predictedId);
                    Console.WriteLine($"[RPC] Skill: bp{bpId} assetId={assetId} pred={predictedId} -> Reject");
                }
            });
        }

        /// <summary>服务器 → 客户端 RPC 回程（payload = NetId + MethodHash + reqId + 参数，与生成代理格式一致）</summary>
        private void SendClientRpc(int bpId, long methodHash, params int[] args)
        {
            var w = new PacketWriter();
            w.WriteUInt32((uint)bpId);   // NetId 低 16 位 = bpId
            w.WriteInt64(methodHash);
            w.WriteUInt32(0);            // reqId = 0（Fire-and-Forget）
            foreach (var a in args) w.WriteInt32(a);
            OnSendClientRpc?.Invoke(bpId, w.ToArray());
        }

        private void InitializeBattle()
        {
            lock (_lock)
            {
                // Load collision world
                _collisionWorld = new CollisionWorld();
                if (Context.CollisionData != null && Context.CollisionData.Length > 0)
                {
                    _collisionWorld = CollisionWorld.LoadFromBytes(Context.CollisionData);
                    Console.WriteLine($"[BattleRoom] Loaded collision snapshot: {_collisionWorld.Count} boxes");
                }
                else if (!string.IsNullOrEmpty(Context.CollisionDataPath) && System.IO.File.Exists(Context.CollisionDataPath))
                {
                    _collisionWorld = CollisionWorld.Load(Context.CollisionDataPath);
                    Console.WriteLine($"[BattleRoom] Loaded collision from {Context.CollisionDataPath}: {_collisionWorld.Count} boxes");
                }
                else
                {
                    _collisionWorld.AddBox(new AABB(new Vec3(-50, -1, -50), new Vec3(50, 0, 50)));
                    Console.WriteLine("[BattleRoom] No collision file. Using default floor.");
                }
                EnsureDefaultGround(_collisionWorld);
                // Build and cache spawn point lookup
                _team1SpawnPoints = new List<SpawnPoint>();
                _team2SpawnPoints = new List<SpawnPoint>();
                _anySpawnPoints = new List<SpawnPoint>();
                _deathmatchSpawnPoints = new List<SpawnPoint>();
                if (Context.SpawnPoints != null && Context.SpawnPoints.Count > 0)
                {
                    foreach (var sp in Context.SpawnPoints)
                    {
                        _deathmatchSpawnPoints.Add(sp);
                        if (sp.TeamId == 1)
                            _team1SpawnPoints.Add(sp);
                        else if (sp.TeamId == 2)
                            _team2SpawnPoints.Add(sp);
                        else
                            _anySpawnPoints.Add(sp);
                    }
                }

                var initialSpawns = new Dictionary<int, SpawnPoint>();

                // Initialize player state
                foreach (var player in Context.Players)
                {
                    int bpId = Context.GetBattlePlayerId(player.UserId);

                    SpawnPoint spawnPoint;
                    if (!IsDeathmatch && player.TeamId == 1 && _team1SpawnPoints.Count > 0)
                    {
                        int idx = _spawnRng.Next(_team1SpawnPoints.Count);
                        spawnPoint = _team1SpawnPoints[idx];
                    }
                    else if (!IsDeathmatch && player.TeamId == 2 && _team2SpawnPoints.Count > 0)
                    {
                        int idx = _spawnRng.Next(_team2SpawnPoints.Count);
                        spawnPoint = _team2SpawnPoints[idx];
                    }
                    else if (IsDeathmatch)
                        spawnPoint = GetInitialDeathmatchSpawnPoint(bpId, _playerIds.Count);
                    else if (_anySpawnPoints.Count > 0)
                        spawnPoint = _anySpawnPoints[_spawnRng.Next(_anySpawnPoints.Count)];
                    else
                    {
                        int idx = _spawnRng.Next(DefaultSpawnPositions.Length);
                        spawnPoint = new SpawnPoint(DefaultSpawnPositions[idx]);
                    }

                    _playerIds.Add(bpId);
                    initialSpawns[bpId] = spawnPoint;

                }

                // Initialize ECS world. Player entity creation is owned by the
                // lifecycle system; the room only supplies spawn data and team metadata.
                _ecsWorld = new ServerECSWorld(_collisionWorld, IsDeathmatch);
                foreach (var bpId in _playerIds)
                {
                    var player = Context.Players.Find(value => Context.GetBattlePlayerId(value.UserId) == bpId);
                    var heroCfg = HeroRegistry.GetHero(player?.HeroId ?? HeroRegistry.DefaultHeroId)
                        ?? HeroRegistry.GetHero(HeroRegistry.DefaultHeroId);
                    var spawnPoint = initialSpawns[bpId];
                    var spawnSnapshot = PlayerSnapshot.Default(spawnPoint.Position);
                    spawnSnapshot.Rotation = Quat.Euler(0f, spawnPoint.Yaw, 0f);
                    _ecsWorld.QueuePlayerSpawn(
                        bpId,
                        spawnSnapshot,
                        heroCfg,
                        player?.TeamId ?? 0);
                }
                _ecsWorld.FlushLifecycleRequests();

                Log($"Battle {BattleId} initialized with {Context.Players.Count} players");
            }
        }

        private static void EnsureDefaultGround(CollisionWorld world)
        {
            if (world == null) return;
            var min = new Vec3(-50, -1, -50);
            var max = new Vec3(50, 0, 50);
            const float epsilon = 0.001f;
            for (int i = 0; i < world.Count; i++)
            {
                var box = world.Boxes[i];
                if (Math.Abs(box.Min.x - min.x) <= epsilon
                    && Math.Abs(box.Min.y - min.y) <= epsilon
                    && Math.Abs(box.Min.z - min.z) <= epsilon
                    && Math.Abs(box.Max.x - max.x) <= epsilon
                    && Math.Abs(box.Max.y - max.y) <= epsilon
                    && Math.Abs(box.Max.z - max.z) <= epsilon)
                    return;
            }
            world.AddBox(new AABB(min, max));
        }

        /// <summary>
        /// Handle BattleReady from a player.
        /// </summary>
        public void HandleBattleReady(int battlePlayerId, string endpoint)
        {
            lock (_lock)
            {
                if (_ecsWorld.IsPlayerDisconnected(battlePlayerId))
                    return;

                _ecsWorld.SetPlayerReady(battlePlayerId, true);
                _playerEndpoints[battlePlayerId] = endpoint;

                Log($"Player {battlePlayerId} ready in battle {BattleId}");

                // 先给发 BattleReady 的客户端回 BattleStart（不等全员）
                SendBattleStart(battlePlayerId, endpoint);

                // 全员就绪后启动帧循环
                if (!_hasStarted && _playerIds.Count >= Context.Players.Count)
                {
                    bool allReady = true;
                    foreach (var playerId in _playerIds)
                        allReady = allReady && _ecsWorld.IsPlayerReady(playerId);

                    if (allReady)
                    {
                        _hasStarted = true;
                        Log($"[BattleRoom] All {Context.Players.Count} players ready, starting frame loop");
                        BroadcastBattleStart();
                        StartFrameLoop();
                    }
                }
            }
        }

        /// <summary>
        /// Handle player input operation.
        /// </summary>
        /// <summary>
        /// RPC 入口（路径 X）：客户端 RpcCall 包经 BattleUdpServer 路由到此。
        /// 解析 NetId + MethodHash → 按 methodHash 分发到服务器侧处理器。
        /// </summary>
        public event Action<int, long> OnRpcCallReceived; // (battlePlayerId, methodHash) 供测试/日志观测
        public event Action<int, byte[]> OnSendClientRpc; // (battlePlayerId, payload) 服务器→客户端 RPC 回程
        private readonly Dictionary<long, Action<int, PacketReader>> _rpcHandlers = new Dictionary<long, Action<int, PacketReader>>();

        /// <summary>注册服务器侧 RPC 处理器（签名与客户端 [ServerRpc] 方法一致）</summary>
        public void RegisterRpcHandler(string fullTypeName, string methodName, string[] paramTypes, Action<int, PacketReader> handler)
        {
            string sig = ShootingGame.Network.RpcMethodHash.BuildSignature(fullTypeName, methodName, paramTypes);
            long hash = ShootingGame.Network.RpcMethodHash.Compute(sig);
            _rpcHandlers[hash] = handler;
            Console.WriteLine($"[RPC] Registered handler 0x{hash:X16} : {sig}");
        }

        public void HandleRpcCall(int battlePlayerId, byte[] payload)
        {
            lock (_lock)
            {
                if (!_hasStarted || _hasEnded)
                    return;
                if (_ecsWorld.IsPlayerDisconnected(battlePlayerId))
                    return;

                if (payload.Length < 12) return; // NetId(4) + MethodHash(8) 最小头部
                try
                {
                    var reader = new PacketReader(payload);
                    uint netId = reader.ReadUInt32();
                    long methodHash = reader.ReadInt64();
                    reader.ReadUInt32(); // reqId（生成代理格式：NetId + MethodHash + reqId + args）
                    Console.WriteLine($"[RPC] bp{battlePlayerId} -> netId={netId} methodHash=0x{methodHash:X8} payload={payload.Length}B");
                    OnRpcCallReceived?.Invoke(battlePlayerId, methodHash);

                    if (_rpcHandlers.TryGetValue(methodHash, out var handler))
                    {
                        handler(battlePlayerId, reader);
                    }
                    else
                    {
                        Console.WriteLine($"[RPC] No handler for methodHash=0x{methodHash:X8} from bp{battlePlayerId}");
                    }                }
                catch (Exception ex)
                {
                    Console.WriteLine($"[RPC] Parse error from bp{battlePlayerId}: {ex.Message}");
                }
            }
        }

        public void HandlePlayerOperation(int battlePlayerId, PlayerOperation operation, int clientFrameId, int clientAckedFrame)
        {
            lock (_lock)
            {
                if (!_hasStarted || _hasEnded)
                    return;

                if (_ecsWorld.IsPlayerDisconnected(battlePlayerId))
                    return;

                if (_ecsWorld.IsPlayerDead(battlePlayerId))
                    return;

                // Update acked frame
                _ecsWorld.UpdateClientAckedFrame(battlePlayerId, clientAckedFrame);

                // Store movement input (will be consumed in frame loop)
                if (_ecsWorld != null)
                {
                    var input = new InputFrame
                    {
                        Tick = clientFrameId,
                        Movement = new Vec2(operation.MoveX, operation.MoveY),
                        AimYaw = operation.AimYaw,
                        AimPitch = operation.AimPitch,
                        Fire = operation.Fire,
                        Jump = operation.Jump,
                        Run = operation.Run,
                        Aim = operation.Aim,
                        Reload = operation.Reload,
                        Crouch = operation.Crouch
                    };
                    _ecsWorld.QueueInput(battlePlayerId, input);

                }



                // Queue attacks for the ECS receive system; deduplication happens on the entity.
                if (operation.AttackOperations != null && operation.AttackOperations.Count > 0)
                    _ecsWorld.QueueAttacks(battlePlayerId, operation.AttackOperations);

                // Process ability events (server-authoritative)
                if (operation.AbilityEvents != null && operation.AbilityEvents.Count > 0)
                {
                    foreach (var evt in operation.AbilityEvents)
                    {
                        switch (evt.EventType)
                        {
                            case AbilityEventType.RequestActivate:
                                ushort instanceId = _ecsWorld.TryActivateAbility(battlePlayerId, evt.AssetId);
                                _pendingAbilityConfirmations.Add(new AbilityEventData
                                {
                                    PlayerId = (byte)battlePlayerId,
                                    InstanceId = evt.InstanceId,
                                    AssetId = evt.AssetId,
                                    EventType = instanceId > 0 ? AbilityEventType.ConfirmActivate : AbilityEventType.RejectActivate
                                });
                                break;
                            case AbilityEventType.Deactivate:
                                var entity = _ecsWorld.GetEntity(battlePlayerId);
                                if (entity.IsValid)
                                    AbilityLifecycleSystem.Deactivate(_ecsWorld.EntityManager, entity, evt.InstanceId);
                                break;
                            case AbilityEventType.Cancel:
                                entity = _ecsWorld.GetEntity(battlePlayerId);
                                if (entity.IsValid)
                                    AbilityLifecycleSystem.Cancel(_ecsWorld.EntityManager, entity, evt.InstanceId);
                                break;
                        }
                    }
                }
            }
        }

        /// <summary>
        /// Handle player disconnect.
        /// </summary>
        public void HandlePlayerDisconnect(int userId)
        {
            int bpId = Context.GetBattlePlayerId(userId);
            if (bpId < 0) return;

            bool shouldEndBattle = false;

            lock (_lock)
            {
                // 玩家还没通过 UDP 连上战斗（BattleReady 未到）→ 不判负，等重连或清理
                if (!_playerEndpoints.ContainsKey(bpId))
                {
                    Log($"Player {bpId} (userId={userId}) disconnected BEFORE UDP battle join. Marking rejoin-pending.");
                    return;
                }

                _ecsWorld.QueuePlayerDisconnect(bpId);
                _ecsWorld.FlushLifecycleRequests();

                Log($"Player {bpId} (userId={userId}) disconnected");

                // 检查是否所有玩家都已断开或死亡（只统计已通过 UDP 加入的玩家）
                if (!_hasEnded)
                {
                    bool allDown = true;
                    bool anyJoined = false;
                    foreach (var playerId in _playerIds)
                    {
                        if (!_playerEndpoints.ContainsKey(playerId))
                            continue; // 还没连上 UDP，不算
                        anyJoined = true;
                        if (!_ecsWorld.IsPlayerDisconnected(playerId) && !_ecsWorld.IsPlayerDead(playerId))
                        {
                            allDown = false;
                            break;
                        }
                    }
                    if (allDown && anyJoined)
                    {
                        Log($"All players down, ending battle {BattleId}");
                        shouldEndBattle = true;
                    }
                }
            }

            // MatchMaker may call this method while holding its own lock. EndBattle
            // must run after releasing the room lock to keep lock ordering acyclic.
            if (shouldEndBattle)
                EndBattle();
        }

        private void BroadcastBattleStart()
        {
            foreach (var kvp in _playerEndpoints)
            {
                SendBattleStart(kvp.Key, kvp.Value);
            }
        }

        private void SendBattleStart(int battlePlayerId, string endpoint)
        {
            // This will be sent via UDP by BattleUdpServer
            // For now, we'll use a callback mechanism
            OnSendBattleStart?.Invoke(battlePlayerId, endpoint);
        }

        public event Action<int, string> OnSendBattleStart;
        public event Action<string, MainPack> OnSendPacket;

        private void StartFrameLoop()
        {
            _frameId = 1;
            _isRunning = true;

            var thread = new Thread(FrameLoop)
            {
                IsBackground = true,
                Name = $"Battle_{BattleId}_FrameLoop"
            };
            _frameThread = thread;
            thread.Start();

            Log($"Battle {BattleId} frame loop started");
        }

        private void FrameLoop()
        {
            var sw = Stopwatch.StartNew();
            long lastTick = sw.ElapsedMilliseconds;
            double accumulator = 0;
            try
            {
                while (_isRunning)
                {
                    long now = sw.ElapsedMilliseconds;
                    long dt = now - lastTick;
                    lastTick = now;
                    accumulator += dt / 1000.0;

                    int stepCount = 0;
                    while (accumulator >= _frameInterval && stepCount < MaxCatchupFrames)
                    {
                        if (_gameOverRetransmitRemaining > 0)
                        {
                            // GameOver retransmission phase: re-send GameOver to all players
                            lock (_lock)
                            {
                                foreach (var kvp in _playerEndpoints)
                                {
                                    SendGameOver(kvp.Value);
                                }
                                _gameOverRetransmitRemaining--;

                                if (_gameOverRetransmitRemaining <= 0)
                                {
                                    _isRunning = false;
                                    _frameHistory.Clear();
                                    _ecsWorld?.Clear();
                                }
                            }
                        }
                        else
                        {
                            bool shouldEnd = false;
                            lock (_lock)
                            {
                                if (IsDeathmatch ? CheckDeathmatchEnd() : IsTeamEliminated())
                                {
                                    shouldEnd = true;
                                }
                                else
                                {
                                    try
                                    {
                                        ProcessFrame();
                                        _frameId++;
                                    }
                                    catch (Exception ex)
                                    {
                                        Console.WriteLine($"[BattleRoom] ProcessFrame ERROR: {ex.Message}\n{ex.StackTrace}");
                                    }
                                }
                            }

                            if (shouldEnd)
                            {
                                EndBattle();
                            }
                        }

                        accumulator -= _frameInterval;
                        stepCount++;
                    }

                    Thread.Sleep(1);
                }
            }
            finally
            {
                sw.Stop();
                lock (_lock)
                {
                    if (_frameThread == Thread.CurrentThread)
                    {
                        _frameThread = null;
                        _ecsWorld?.Clear();
                    }
                }
            }
        }

        private void ProcessFrame()
        {
            var frameOp = new AllPlayerOperation
            {
                FrameId = _frameId
            };

            // 0.5. 连发扩散热度衰减
            DecayBloomHeat();

            // Network input is applied by ServerNetworkReceiveSystem on the World thread.
            _ecsWorld.Tick();
            _damageEvents.Clear();
            _ecsWorld.ConsumeDamageEvents(_damageEvents);
            AppendDamageEvents();
            _snapshotMessages.Clear();
            _ecsWorld.ConsumeSnapshots(_snapshotMessages);
            var respawnedPlayers = new List<int>();
            _ecsWorld.ConsumeRespawnRequests(respawnedPlayers);
            foreach (var bpId in respawnedPlayers)
                RespawnPlayer(bpId);

            // Build the legacy protocol operation from the ECS input that drove this tick.
            foreach (var bpId in _playerIds)
            {
                if (_ecsWorld.IsPlayerDisconnected(bpId) || _ecsWorld.IsPlayerDead(bpId))
                    continue;

                var input = _ecsWorld.GetCurrentInput(bpId);

                var op = new PlayerOperation
                {
                    PlayerId = bpId,
                    MoveX = input.Movement.x,
                    MoveY = input.Movement.y,
                    AimYaw = input.AimYaw,
                    AimPitch = input.AimPitch,
                    Fire = input.Fire,
                    Jump = input.Jump,
                    Run = input.Run,
                    Aim = input.Aim,
                    Reload = input.Reload
                };

                _ecsWorld.ConsumeAttackOperations(bpId, op.AttackOperations);

                frameOp.Operations.Add(op);
            }

            foreach (var bpId in _playerIds)
            {
                var entity = _ecsWorld.GetEntity(bpId);
                if (!entity.IsValid || !_ecsWorld.EntityManager.IsValid(entity))
                    continue;

                if (!_ecsWorld.TryBuildCurrentSnapshot(bpId, _frameId, out var snapshot))
                    continue;
                snapshot.Tick = _frameId;
                _ecsWorld.RecordPlayerPosition(bpId, _frameId, snapshot.Position);
            }

            // 5. Pack player states
            PackPlayerStates(frameOp);

            // 6. Add hit events
            frameOp.HitEvents.AddRange(_pendingHitEvents);
            _pendingHitEvents.Clear();

            // 6b. Add ability confirmations (server→client)
            if (_pendingAbilityConfirmations.Count > 0)
            {
                frameOp.AbilityEvents.AddRange(_pendingAbilityConfirmations);
                _pendingAbilityConfirmations.Clear();
            }

            // 7. Store frame history
            _frameHistory[_frameId] = frameOp;

            // Trim history
            while (_frameHistory.Count > MaxFrameHistory)
            {
                int oldest = _frameId - MaxFrameHistory;
                _frameHistory.Remove(oldest);
            }

            // 8. Broadcast frame
            BroadcastFrame(frameOp);
        }

        private void AppendDamageEvents()
        {
            for (int i = 0; i < _damageEvents.Count; i++)
            {
                var applied = _damageEvents[i];
                var detected = applied.Hit;
                if (applied.IsKill)
                {
                    _killerPlayerId = detected.AttackerId;
                    _killerTeamId = _ecsWorld.GetPlayerTeam(detected.AttackerId);
                    HandleDeathmatchDeath(detected.VictimId);
                    int lives = DeathmatchRules.GetRemainingLives(_ecsWorld.GetPlayerScore(detected.VictimId).Deaths);
                    Log($"Player {detected.VictimId} killed by {detected.AttackerId} (K:{_ecsWorld.GetPlayerScore(detected.AttackerId).Kills}, lives:{lives})");
                }

                _pendingHitEvents.Add(new HitEventMsg
                {
                    AttackId = detected.AttackId,
                    AttackerId = detected.AttackerId,
                    VictimId = detected.VictimId,
                    Damage = applied.Damage,
                    IsKill = applied.IsKill,
                    HitPoint = detected.HitPoint,
                    HitFrameId = detected.HitFrameId,
                    BodyPart = detected.BodyPart
                });
            }
        }

        private bool ApplyPlayerDamage(int attackerId, int attackerTeamId, int targetId, int damage)
        {
            var result = _ecsWorld.ApplyCombatDamage(attackerId, targetId, damage, GameConstants.RespawnDelay);
            if (!result.WasApplied)
                return false;

            if (result.IsKill)
            {
                _killerPlayerId = attackerId;
                _killerTeamId = attackerTeamId;
                HandleDeathmatchDeath(targetId);
                var attackerScore = _ecsWorld.GetPlayerScore(attackerId);
                int lives = DeathmatchRules.GetRemainingLives(_ecsWorld.GetPlayerScore(targetId).Deaths);
                Log($"Player {targetId} killed by {attackerId} (K:{attackerScore.Kills}, lives:{lives})");
            }

            return result.IsKill;
        }

        private void HandleDeathmatchDeath(int victimId)
        {
            if (!IsDeathmatch)
                return;

            int deaths = _ecsWorld.GetPlayerScore(victimId).Deaths;
            if (!DeathmatchRules.ShouldRespawn(deaths))
            {
                _ecsWorld.EliminatePlayer(victimId);
                Log($"Player {victimId} exhausted all {DeathmatchRules.LivesPerPlayer} lives and was eliminated");
            }
        }

        private Vec3 GetHistoricalPosition(int bpId, int frameId)
        {
            if (_ecsWorld.TryGetHistoricalPosition(bpId, frameId, out var pos))
                return pos;

            return _ecsWorld.TryGetSnapshot(bpId, _frameId, out var snap) ? snap.Position : Vec3.Zero;
        }

        private GunConfigData GetPlayerGun(int bpId)
        {
            return _ecsWorld.GetPlayerGun(bpId);
        }

        /// <summary>连发扩散热度随时间恢复</summary>
        private void DecayBloomHeat()
        {
            foreach (var bpId in _playerIds)
            {
                var gun = GetPlayerGun(bpId);
                if (gun == null || gun.BloomRecover <= 0f) continue;
                if (!_ecsWorld.TryGetWeaponRuntime(bpId, out var runtime)
                    || runtime.BloomHeat <= 0f)
                    continue;

                runtime.BloomHeat = Math.Max(0f, runtime.BloomHeat - gun.BloomRecover * _frameInterval);
                _ecsWorld.SetWeaponRuntime(bpId, runtime);
            }
        }

        private void SpawnBullets(AllPlayerOperation frameOp)
        {
            foreach (var op in frameOp.Operations)
            {
                if (op.AttackOperations == null || op.AttackOperations.Count == 0)
                    continue;

                int bpId = op.PlayerId;
                if (!_ecsWorld.TryGetSnapshot(bpId, _frameId, out var snapshot))
                    continue;

                // 服务端权威弹药检查：换弹中或弹药不足时忽略攻击
                if (snapshot.IsReloading || snapshot.CurrentAmmo <= 0)
                    continue;

                int teamId = _ecsWorld.GetPlayerTeam(bpId);
                var gun = GetPlayerGun(bpId);
                float bulletSpeed = gun != null ? gun.BulletSpeed : 100f;
                float maxRange = gun != null ? gun.Range : 200f;

                foreach (var atk in op.AttackOperations)
                {
                    int originalClientFrame = atk.ClientFrameId; // 保留原始客户端帧号用于射速检查

                    int clientFrame = originalClientFrame;
                    if (clientFrame > _frameId)
                        clientFrame = _frameId;

                    // 服务端射速校验（用原始客户端帧号，不受 _frameId 截断影响；
                    // 否则服务器 tick 慢于客户端时两次攻击被截成同一帧，差=0→永远拒绝）
                    _ecsWorld.TryGetWeaponRuntime(bpId, out var weaponRuntime);
                    if (gun != null && weaponRuntime.HasLastFireFrame)
                    {
                        float interval = (originalClientFrame - weaponRuntime.LastFireFrame) * _frameInterval;
                        if (interval < gun.FireRate * 0.5f)
                        {
                            Log($"[AntiCheat] bp{bpId} 射速过快: {interval:F3}s < {gun.FireRate * 0.5f:F3}s, 丢弃攻击");
                            continue;
                        }
                    }
                    weaponRuntime.HasLastFireFrame = true;
                    weaponRuntime.LastFireFrame = originalClientFrame;

                    // 优先使用客户端发送的枪口位置（非零表示客户端已设置）
                    Vec3 spawnPos;
                    if (atk.SpawnPos.x != 0f || atk.SpawnPos.y != 0f || atk.SpawnPos.z != 0f)
                    {
                        spawnPos = atk.SpawnPos;
                    }
                    else
                    {
                        // 回退：从历史位置计算
                        spawnPos = GetHistoricalPosition(bpId, clientFrame);
                        spawnPos = spawnPos + new Vec3(0, GameConstants.PlayerHeight * 0.85f, 0);
                    }

                    // Write back spawn position for client visual bullets
                    atk.SpawnPos = spawnPos;

                    // Direction from AttackOperation's stored values (correct for the frame it was fired)
                    float aimYaw = MathF.Atan2(atk.TowardX, atk.TowardY) * (180f / MathF.PI);
                    var aimRot = Quat.Euler(atk.AimPitch, aimYaw, 0);
                    Vec3 dir = aimRot * Vec3.Forward;
                    dir = dir.Normalized;

                    // 扩散：基础散射 + 移动惩罚 + 连发 bloom（双端同种子，客户端视觉弹道一致）
                    if (gun != null)
                    {
                        bool isMoving = new Vec3(snapshot.Velocity.x, 0f, snapshot.Velocity.z).SqrMagnitude > 1f;
                        float heat = weaponRuntime.BloomHeat;
                        float spreadDeg = SpreadUtility.ComputeTotalSpread(gun, isMoving, heat);
                        dir = SpreadUtility.ApplyConeSpread(dir, spreadDeg, SpreadUtility.MakeSeed(atk.AttackId, bpId));
                        weaponRuntime.BloomHeat = Math.Min(heat + gun.BloomPerShot,
                            gun.BloomMax > 0f ? gun.BloomMax : heat + gun.BloomPerShot);
                    }

                    _ecsWorld.SetWeaponRuntime(bpId, weaponRuntime);

                    // Lag compensation: frame-by-frame catchup with collision detection
                    int catchupFrames = _frameId - clientFrame;
                    if (_getPlayerRtt != null && catchupFrames > 0)
                    {
                        float rtt = _getPlayerRtt(bpId);
                        int maxCatchupFromRtt = (int)(rtt / _frameInterval) + 2;
                        catchupFrames = Math.Min(catchupFrames, maxCatchupFromRtt);
                    }

                    Vec3 currentPos = spawnPos;
                    float traveledDistance = 0f;
                    bool hitDuringCatchup = false;

                    // Frame-by-frame simulation with swept collision to prevent tunneling
                    int framesSimulated = 0;
                    while (framesSimulated <= catchupFrames)
                    {
                        Vec3 prevPos = currentPos;
                        float stepDist = bulletSpeed * _frameInterval;
                        currentPos = currentPos + dir * stepDist;
                        traveledDistance += stepDist;
                        framesSimulated++;

                        // Check max distance
                        if (traveledDistance >= maxRange)
                            break;

                        // Check world collision during catchup (bullet vs obstacles)
                        var worldHit = _collisionWorld.SweepSphere(prevPos, GameConstants.BulletRadius, dir, stepDist);
                        if (worldHit.Hit)
                            break;

                        // Check swept collision during catchup
                        foreach (var targetId in _playerIds)
                        {
                            if (!_ecsWorld.CanReceiveCombatDamage(bpId, targetId, IsDeathmatch))
                                continue;

                            // Use the target's position at the corresponding catchup frame
                            Vec3 targetPos;
                            if (framesSimulated < catchupFrames)
                            {
                                int historyFrame = clientFrame + framesSimulated;
                                targetPos = _ecsWorld.GetCombatTargetPosition(targetId, historyFrame, _frameId);
                            }
                            else
                            {
                                targetPos = _ecsWorld.GetCombatTargetPosition(targetId, _frameId, _frameId);
                            }

                            // 商用级扫描碰撞：子弹路径(prevPos→currentPos) vs 命中胶囊体
                            var hitCapsule = new Capsule(targetPos - new Vec3(0, GameConstants.FootCapsuleOffset, 0), GameConstants.PlayerHeight + GameConstants.FootCapsuleOffset, GameConstants.HitCapsuleRadius);
                            if (Intersection.SweepBulletHitCapsule(prevPos, currentPos, hitCapsule, GameConstants.BulletRadius))
                            {
                                // Hit during catchup! Calculate body-part damage (枪械伤害 × 距离衰减 × 部位倍率)
                                int baseDamage = gun != null
                                    ? (int)(gun.Damage * gun.GetFalloffMultiplier(traveledDistance) + 0.5f)
                                    : GameConstants.HitscanDamage;
                                int damage = CalculateBodyPartDamage(baseDamage, currentPos, targetPos, out int bodyPart);
                                damage = ApplyTagDamageModifiers(damage, bpId, targetId);
                                bool isKill = ApplyPlayerDamage(bpId, teamId, targetId, damage);

                                _pendingHitEvents.Add(new HitEventMsg
                                {
                                    AttackId = atk.AttackId,
                                    AttackerId = bpId,
                                    VictimId = targetId,
                                    Damage = damage,
                                    IsKill = isKill,
                                    HitPoint = currentPos,
                                    HitFrameId = _frameId,
                                    BodyPart = bodyPart
                                });

                                Log($"[Hit-Catchup] bp{bpId} hit bp{targetId} for {damage} damage (kill={isKill}) frameDiff={catchupFrames}");
                                hitDuringCatchup = true;
                                break;
                            }
                        }

                        if (hitDuringCatchup)
                            break;
                    }

                    if (!hitDuringCatchup && traveledDistance < maxRange)
                    {
                        _ecsWorld.SpawnProjectile(new ProjectileComponent
                        {
                            AttackId = atk.AttackId,
                            OwnerId = bpId,
                            OwnerTeamId = teamId,
                            Position = currentPos,
                            Direction = dir,
                            Speed = bulletSpeed,
                            MaxDistance = maxRange,
                            Damage = gun != null ? gun.Damage : GameConstants.HitscanDamage,
                            Gun = gun,
                            SpawnFrameId = clientFrame,
                            TraveledDistance = traveledDistance
                        });
                    }
                }
            }
        }

        private void TickBullets()
        {
            var bullets = new List<Entity>();
            var toRemove = new List<Entity>();
            _ecsWorld.GetProjectileEntities(bullets);

            foreach (var bulletEntity in bullets)
            {
                if (!_ecsWorld.EntityManager.IsValid(bulletEntity))
                    continue;

                ref var bullet = ref _ecsWorld.EntityManager.GetComponent<ProjectileComponent>(bulletEntity);
                // 保存移动前位置，用于扫描碰撞检测
                Vec3 prevPos = bullet.Position;

                // Move
                bullet.Position = bullet.Position + bullet.Direction * (bullet.Speed * _frameInterval);
                bullet.TraveledDistance += bullet.Speed * _frameInterval;

                // Check max distance
                if (bullet.TraveledDistance >= bullet.MaxDistance)
                {
                    toRemove.Add(bulletEntity);
                    continue;
                }

                // Check world collision (bullets cannot pass through obstacles)
                float moveDist = bullet.Speed * _frameInterval;
                var worldHit = _collisionWorld.SweepSphere(prevPos, GameConstants.BulletRadius, bullet.Direction, moveDist);
                if (worldHit.Hit)
                {
                    toRemove.Add(bulletEntity);
                    continue;
                }

                // Check swept collision with players
                foreach (var targetId in _playerIds)
                {
                    if (!_ecsWorld.CanReceiveCombatDamage(bullet.OwnerId, targetId, IsDeathmatch))
                        continue;

                    var targetPos = _ecsWorld.GetSnapshot(targetId, _frameId).Position;
                    targetPos = _ecsWorld.GetCombatTargetPosition(targetId, _frameId, _frameId);

                    // 商用级扫描碰撞：子弹路径(prevPos→newPos) vs 命中胶囊体
                    // 使用比物理碰撞更宽松的 HitCapsuleRadius，且扫描整段路径防止穿透
                    var hitCapsule = new Capsule(targetPos - new Vec3(0, GameConstants.FootCapsuleOffset, 0), GameConstants.PlayerHeight + GameConstants.FootCapsuleOffset, GameConstants.HitCapsuleRadius);
                    if (Intersection.SweepBulletHitCapsule(prevPos, bullet.Position, hitCapsule, GameConstants.BulletRadius))
                    {
                        // Hit! Calculate body-part damage (含距离衰减)
                        int bulletBaseDamage = bullet.Gun != null
                            ? (int)(bullet.Gun.Damage * bullet.Gun.GetFalloffMultiplier(bullet.TraveledDistance) + 0.5f)
                            : bullet.Damage;
                        int damage = CalculateBodyPartDamage(bulletBaseDamage, bullet.Position, targetPos, out int bodyPart);
                        damage = ApplyTagDamageModifiers(damage, bullet.OwnerId, targetId);
                        bool isKill = ApplyPlayerDamage(
                            bullet.OwnerId,
                            bullet.OwnerTeamId,
                            targetId,
                            damage);

                        var hitEvent = new HitEventMsg
                        {
                            AttackId = bullet.AttackId,
                            AttackerId = bullet.OwnerId,
                            VictimId = targetId,
                            Damage = damage,
                            IsKill = isKill,
                            HitPoint = bullet.Position,
                            HitFrameId = _frameId,
                            BodyPart = bodyPart
                        };

                        _pendingHitEvents.Add(hitEvent);
                        toRemove.Add(bulletEntity);
                        Log($"[Hit] bp{bullet.OwnerId} hit bp{targetId} for {damage} damage (kill={isKill})");
                        break;
                    }
                }
            }

            foreach (var bulletEntity in toRemove)
                _ecsWorld.DestroyProjectile(bulletEntity);
        }

        private void RespawnPlayer(int bpId)
        {
            if (IsDeathmatch && !DeathmatchRules.ShouldRespawn(_ecsWorld.GetPlayerScore(bpId).Deaths))
            {
                _ecsWorld.EliminatePlayer(bpId);
                return;
            }

            int teamId = _ecsWorld.GetPlayerTeam(bpId);
            SpawnPoint spawnPoint = GetRespawnPoint(bpId, teamId);
            int maxHp = _ecsWorld.GetPlayerMaxHealth(bpId);

            var snap = PlayerSnapshot.Default(spawnPoint.Position);
            snap.Rotation = Quat.Euler(0f, spawnPoint.Yaw, 0f);
            _ecsWorld.ApplyPlayerLoadoutToSnapshot(bpId, ref snap);
            snap.Health = (byte)Math.Max(0, Math.Min(byte.MaxValue, maxHp));
            _ecsWorld.CompleteRespawn(bpId, snap);

            Log($"Player {bpId} respawned at ({spawnPoint.Position.x:F1}, {spawnPoint.Position.y:F1}, {spawnPoint.Position.z:F1}) yaw={spawnPoint.Yaw:F1}");
        }

        private SpawnPoint GetRespawnPoint(int bpId, int teamId)
        {
            if (IsDeathmatch)
                return GetDeathmatchSpawnPoint(bpId);

            var pool = teamId == 1 ? _team1SpawnPoints :
                       teamId == 2 ? _team2SpawnPoints :
                       _anySpawnPoints;

            if (pool == null || pool.Count == 0)
                pool = _anySpawnPoints;

            if (pool != null && pool.Count > 0)
            {
                var sp = pool[_spawnRng.Next(pool.Count)];
                return sp;
            }

            return GetFallbackSpawnPoint(bpId);
        }

        private SpawnPoint GetInitialDeathmatchSpawnPoint(int bpId, int playerOrdinal)
        {
            if (_deathmatchSpawnPoints.Count == 0)
                return GetFallbackSpawnPoint(bpId);

            int index = playerOrdinal % _deathmatchSpawnPoints.Count;
            _lastDeathmatchSpawnIndex[bpId] = index;
            return _deathmatchSpawnPoints[index];
        }

        private SpawnPoint GetDeathmatchSpawnPoint(int bpId)
        {
            if (_deathmatchSpawnPoints.Count == 0)
                return GetFallbackSpawnPoint(bpId);

            var enemyPositions = new List<Vec3>();
            foreach (var otherPlayerId in _playerIds)
            {
                if (otherPlayerId == bpId
                    || _ecsWorld.IsPlayerDisconnected(otherPlayerId)
                    || _ecsWorld.IsPlayerDead(otherPlayerId))
                    continue;

                if (_ecsWorld.TryBuildCurrentSnapshot(otherPlayerId, _frameId, out var snapshot))
                    enemyPositions.Add(snapshot.Position);
            }

            int previousIndex = _lastDeathmatchSpawnIndex.TryGetValue(bpId, out int index) ? index : -1;
            var selected = DeathmatchSpawnSelector.Select(
                _deathmatchSpawnPoints,
                enemyPositions,
                previousIndex,
                IsSpawnPointValid);
            _lastDeathmatchSpawnIndex[bpId] = selected.Index;
            return selected.SpawnPoint;
        }

        private bool IsSpawnPointValid(SpawnPoint spawnPoint)
        {
            // Lift the capsule slightly so standing on the floor is not treated as overlap.
            var position = spawnPoint.Position + new Vec3(0f, 0.05f, 0f);
            return !_collisionWorld.OverlapCapsule(Capsule.Player(position));
        }

        private static SpawnPoint GetFallbackSpawnPoint(int bpId)
        {
            Vec3 position = bpId >= 0 && bpId < DefaultSpawnPositions.Length
                ? DefaultSpawnPositions[bpId]
                : new Vec3(bpId * 2, 0, 0);
            return new SpawnPoint(position);
        }

        /// <summary>
        /// 死斗结束判定：仅剩一名仍有生命的玩家，或对局时间耗尽。
        /// 时间耗尽时剩余生命最多者胜，再比较击杀、死亡和 bpId。
        /// </summary>
        private bool CheckDeathmatchEnd()
        {
            bool hasUnavailablePlayer = false;
            var playerStates = new List<DeathmatchPlayerState>();
            foreach (var bpId in _playerIds)
            {
                var score = _ecsWorld.GetPlayerScore(bpId);
                bool isDisconnected = _ecsWorld.IsPlayerDisconnected(bpId);
                hasUnavailablePlayer = hasUnavailablePlayer
                    || isDisconnected
                    || DeathmatchRules.GetRemainingLives(score.Deaths) == 0;
                playerStates.Add(new DeathmatchPlayerState(bpId, score.Deaths, isDisconnected));
            }

            if (hasUnavailablePlayer && DeathmatchRules.TryGetLastSurvivor(playerStates, out int survivor))
            {
                _killerPlayerId = survivor;
                return true;
            }

            if (ServerMatchClock.GetRemainingTicks(_frameId, Context.TimeLimit, _frameInterval) <= 0)
            {
                int bestBp = -1, bestLives = -1, bestKills = -1, bestDeaths = int.MaxValue;
                foreach (var bpId in _playerIds)
                {
                    if (_ecsWorld.IsPlayerDisconnected(bpId))
                        continue;

                    var score = _ecsWorld.GetPlayerScore(bpId);
                    int lives = DeathmatchRules.GetRemainingLives(score.Deaths);
                    if (lives > bestLives
                        || (lives == bestLives && score.Kills > bestKills)
                        || (lives == bestLives && score.Kills == bestKills && score.Deaths < bestDeaths)
                        || (lives == bestLives && score.Kills == bestKills && score.Deaths == bestDeaths && (bestBp < 0 || bpId < bestBp)))
                    {
                        bestBp = bpId;
                        bestLives = lives;
                        bestKills = score.Kills;
                        bestDeaths = score.Deaths;
                    }
                }
                _killerPlayerId = bestBp;
                return true;
            }

            return false;
        }

        private bool IsTeamEliminated()
        {
            // 还有玩家未通过 UDP 加入（BattleReady 未到）且未断开 → 不判定胜负（可能在加载场景）
            foreach (var bpId in _playerIds)
            {
                if (!_playerEndpoints.ContainsKey(bpId) && !_ecsWorld.IsPlayerDisconnected(bpId))
                    return false;
            }

            if (ServerMatchClock.GetRemainingTicks(_frameId, Context.TimeLimit, _frameInterval) <= 0)
            {
                ServerMatchClock.ResolveTeamTimeLimitWinner(
                    _frameHistory,
                    _frameId,
                    Context,
                    out _killerPlayerId,
                    out _killerTeamId);
                return true;
            }

            bool team1Alive = false, team2Alive = false;
            foreach (var bpId in _playerIds)
            {
                if (_ecsWorld.IsPlayerDisconnected(bpId))
                    continue;
                if (_ecsWorld.IsPlayerDead(bpId))
                    continue;

                int teamId = _ecsWorld.GetPlayerTeam(bpId);
                if (teamId == 1) team1Alive = true;
                else if (teamId == 2) team2Alive = true;
            }

            if (!team1Alive && !team2Alive) return false; // no players at all
            if (!team1Alive) { _killerTeamId = 2; return true; }
            if (!team2Alive) { _killerTeamId = 1; return true; }
            return false;
        }

        private void PackPlayerStates(AllPlayerOperation frameOp)
        {
            foreach (var bpId in _playerIds)
            {
                if (!_ecsWorld.TryBuildCurrentSnapshot(bpId, _frameId, out var snap))
                    continue;
                snap.Tick = _frameId;

                float rotationY = snap.Rotation.EulerAngles.y;
                float speed = snap.Velocity.Magnitude;
                bool isRunning = speed > GameConstants.MoveSpeed + 0.1f;


                // 收集能力实例数据
                List<AbilityInstanceData> activeAbilities = null;
                if (snap.ActiveAbilities != null && snap.ActiveAbilityCount > 0)
                {
                    activeAbilities = new List<AbilityInstanceData>();
                    int count = Math.Min(snap.ActiveAbilityCount, (byte)snap.ActiveAbilities.Length);
                    for (int i = 0; i < count; i++)
                    {
                        var ability = snap.ActiveAbilities[i];
                        if (ability.AssetId != 0 && !ability.IsFinished)
                            activeAbilities.Add(ability);
                    }
                }

                frameOp.PlayerStates.Add(new PlayerStateMsg
                {
                    PlayerId = bpId,
                    Position = snap.Position,
                    Hp = snap.Health,
                    IsDead = snap.Health <= 0,
                    Velocity = snap.Velocity,
                    VerticalVelocity = snap.VerticalVelocity,
                    IsGrounded = snap.IsGrounded,
                    StateEnum = (int)snap.State,
                    FireCooldown = snap.FireCooldown,
                    RotationY = rotationY,
                    IsRunning = isRunning,
                    IsAiming = _ecsWorld.GetCurrentInput(bpId).Aim,
                    IsCrouching = _ecsWorld.GetCurrentInput(bpId).Crouch,
                    CurrentAmmo = snap.CurrentAmmo,
                    IsReloading = snap.IsReloading,
                    TagBitmask = snap.TagBitmask,
                    ActiveAbilities = activeAbilities,
                    MaxHp = _ecsWorld.GetPlayerMaxHealth(bpId),
                    Kills = _ecsWorld.GetPlayerScore(bpId).Kills,
                    Deaths = _ecsWorld.GetPlayerScore(bpId).Deaths
                });
            }
        }

        private void BroadcastFrame(AllPlayerOperation frameOp)
        {
            foreach (var kvp in _playerEndpoints)
            {
                int bpId = kvp.Key;
                string endpoint = kvp.Value;

                // 构建包
                var pack = new MainPack
                {
                    RequestCode = RequestCode.Battle,
                    ActionCode = ActionCode.BattleFrame,
                    Timestamp = ServerMatchClock.GetRemainingTicks(_frameId, Context.TimeLimit, _frameInterval),
                    BattleInfo = new BattleInfo
                    {
                        OperationId = _frameId,
                        BattleId = BattleId
                    }
                };

                // 只广播最新 1 帧（不做 ack 补发——客户端插值缓冲自行平滑丢帧，
                // 避免 ack 落后时一次广播几十帧淹没客户端主线程）
                if (_frameHistory.TryGetValue(_frameId, out var historyFrame))
                {
                    pack.BattleInfo.AllPlayerOperations.Add(historyFrame);
                }

                // Add hit events
                pack.BattleInfo.HitEvents.AddRange(frameOp.HitEvents);

                OnSendPacket?.Invoke(endpoint, pack);
            }
        }

        private void EndBattle()
        {
            bool shouldNotifyMatchMaker = false;
            lock (_lock)
            {
                if (_hasEnded) return;

                _hasEnded = true;
                _gameOverRetransmitRemaining = GameOverRetransmitTicks;

                Log($"Battle {BattleId} ended. Winner team: {_killerTeamId}");

                // Clean up gameplay state (no more simulation)
                _ecsWorld.ClearProjectiles();
                shouldNotifyMatchMaker = true;
            }

            // Never call back into MatchMaker while holding BattleRoom._lock.
            if (shouldNotifyMatchMaker)
                _matchMaker?.EndBattle(BattleId);
        }

        /// <summary>
        /// 发送 GameOver 包给指定玩家（可重复调用以确保可靠送达）。
        /// </summary>
        private void SendGameOver(string endpoint)
        {
            var pack = new MainPack
            {
                RequestCode = RequestCode.Battle,
                ActionCode = ActionCode.GameOver,
                // IntVal: 0=团队模式(Str=胜利队伍ID) 1=死斗(Str=胜者 bpId)
                IntVal = Context.Mode,
                Str = IsDeathmatch ? _killerPlayerId.ToString() : _killerTeamId.ToString()
            };

            // 记分板（按击杀降序，平手比死亡少）
            var entries = new List<ScoreEntryMsg>();
            foreach (var bpId in _playerIds)
            {
                var player = Context.Players.Find(pl => Context.GetBattlePlayerId(pl.UserId) == bpId);
                var score = _ecsWorld.GetPlayerScore(bpId);
                entries.Add(new ScoreEntryMsg
                {
                    PlayerId = bpId,
                    PlayerName = player != null ? player.Username : $"Player_{bpId}",
                    Kills = score.Kills,
                    Deaths = score.Deaths
                });
            }
            entries.Sort((a, b) => b.Kills != a.Kills ? b.Kills - a.Kills : a.Deaths - b.Deaths);
            pack.ScoreEntries.AddRange(entries);

            OnSendPacket?.Invoke(endpoint, pack);
        }

        public void Stop()
        {
            Thread frameThread;
            lock (_lock)
            {
                _isRunning = false;
                frameThread = _frameThread;
                if (frameThread == Thread.CurrentThread)
                    return;
            }

            if (frameThread != null && frameThread.IsAlive)
            {
                frameThread.Join(1000);
                if (frameThread.IsAlive)
                    return;
            }

            lock (_lock)
            {
                if (_frameThread != null && _frameThread.IsAlive)
                    return;
                _frameThread = null;
                _ecsWorld?.Clear();
            }
        }

        /// <summary>
        /// Apply tag-based damage modifiers from victim and attacker buff tags.
        /// </summary>
        private int ApplyTagDamageModifiers(int damage, int attackerId, int victimId)
        {
            // Shield: victim damage resistance (-60%)
            var victimEntity = _ecsWorld.GetEntity(victimId);
            if (victimEntity.IsValid && _ecsWorld.EntityManager.HasComponent<TagComponent>(victimEntity))
            {
                var vTags = _ecsWorld.EntityManager.GetComponent<TagComponent>(victimEntity);
                if (GameplayTagConfig.Tag_Buff_DamageResist.Matches(vTags.TagBitMask))
                    damage = (int)Math.Ceiling(damage * 0.4f);
            }

            // Legacy path: MarkShot uses the current 1.5x multiplier.
            if (damage > 0)
            {
                var attackerEntity = _ecsWorld.GetEntity(attackerId);
                if (attackerEntity.IsValid && _ecsWorld.EntityManager.HasComponent<TagComponent>(attackerEntity))
                {
                    var aTags = _ecsWorld.EntityManager.GetComponent<TagComponent>(attackerEntity);
                    if (GameplayTagConfig.Tag_Buff_DamageBoost.Matches(aTags.TagBitMask))
                    {
                        damage = (int)Math.Ceiling(damage * 1.5f);
                        // Consume the Buff.DamageBoost tag
                        aTags.TagBitMask &= ~GameplayTagConfig.Tag_Buff_DamageBoost.SelfMask;
                        _ecsWorld.EntityManager.SetComponent(attackerEntity, aTags);
                    }
                }
            }

            return Math.Max(1, damage);
        }

        private int CalculateBodyPartDamage(int baseDamage, Vec3 hitPoint, Vec3 playerBasePos)
        {
            return CalculateBodyPartDamage(baseDamage, hitPoint, playerBasePos, out _);
        }

        /// <summary>部位: 0=胸 1=头 2=腹 3=四肢</summary>
        private int CalculateBodyPartDamage(int baseDamage, Vec3 hitPoint, Vec3 playerBasePos, out int bodyPart)
        {
            float relativeY = hitPoint.y - playerBasePos.y;
            float ratio = relativeY / GameConstants.PlayerHeight;

            float multiplier;
            if (ratio >= GameConstants.HeadHeightRatio)
            {
                multiplier = GameConstants.HeadDamageMultiplier;
                bodyPart = 1;
            }
            else if (ratio >= GameConstants.ChestHeightRatio)
            {
                multiplier = GameConstants.ChestDamageMultiplier;
                bodyPart = 0;
            }
            else if (ratio >= GameConstants.AbdomenHeightRatio)
            {
                multiplier = GameConstants.AbdomenDamageMultiplier;
                bodyPart = 2;
            }
            else
            {
                multiplier = GameConstants.LimbDamageMultiplier;
                bodyPart = 3;
            }

            return Math.Max(1, (int)(baseDamage * multiplier));
        }

        private void Log(string message)
        {
            Console.WriteLine($"[BattleRoom {BattleId}] {DateTime.Now:HH:mm:ss.fff} {message}");
        }
    }

}
