// <auto-generated /> (手写版——RPC 代理 + 分发)
using ShootingGame.Network;
using ShootingGame.Shared.Math;
using ShootingGame.Shared.Protocol;

public partial class PlayerCombatBehaviour
{
    // ===== Method Hash =====
    // SHA256("PlayerCombatBehaviour.RequestShoot(Single,Single,Single,Int32)").Int64
    private const long HASH_RequestShoot = unchecked((long)0xA3B2C1D4E5F60718);

    // ===== 静态注册 =====
    static PlayerCombatBehaviour()
    {
        RpcMethodRegistry.Register(HASH_RequestShoot, __RpcHandler_RequestShoot);
    }

    // ===== ServerRpc 代理（客户端调用发送 → 服务端执行） =====
    public void InvokeServerRpc_RequestShoot(float towardX, float towardY, float aimPitch, int clientFrameId)
    {
        var w = new PacketWriter();
        w.WriteUInt32(NetId);
        w.WriteInt64(HASH_RequestShoot);
        w.WriteUInt32(0); // reqId
        w.WriteFloat(towardX);
        w.WriteFloat(towardY);
        w.WriteFloat(aimPitch);
        w.WriteInt32(clientFrameId);
        SendServerRpc(w.ToArray());
    }

    // ===== ServerRpc 分发处理（服务端收到 RPC → 调用原始方法体） =====
    private static void __RpcHandler_RequestShoot(NetworkBehaviour target, PacketReader r)
    {
        var self = (PlayerCombatBehaviour)target;
        var towardX = r.ReadFloat();
        var towardY = r.ReadFloat();
        var aimPitch = r.ReadFloat();
        var clientFrameId = r.ReadInt32();
        self.RequestShoot(towardX, towardY, aimPitch, clientFrameId);
    }
}
