using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

/// <summary>
/// 从 GameplayTagConfigAsset 生成 C# 标签配置代码。
/// 生成文件放在共享库和客户端镜像目录。
/// GameplayTagConfig.cs 通过 #include 或手动粘贴来使用生成的代码。
/// </summary>
public class GameplayTagCodeGenerator : AssetPostprocessor
{
    private const string GeneratedFile = "GameplayTagConfig_gen.cs";
    private const string ServerDir = "Server/ShootingGame.Shared/GameplayTags";
    private const string ClientDir = "Assets/Scripts/Network/Shared/GameplayTags";

    [MenuItem("Tools/GameplayTag/Generate Code")]
    public static void Generate()
    {
        var asset = FindConfigAsset();
        if (asset == null)
        {
            Debug.LogError("[GameplayTagCodeGenerator] GameplayTagConfigAsset not found. Create one via Create → ShootingGame → GameplayTag Config.");
            return;
        }

        string code = GenerateCode(asset.Tags);
        string projectRoot = Application.dataPath.Replace("/", "Assets");
        if (projectRoot.EndsWith("/"))
            projectRoot = projectRoot.Substring(0, projectRoot.Length - 1);

        // Write to server shared library
        string serverPath = Path.Combine(projectRoot, ServerDir, GeneratedFile);
        WriteFile(serverPath, code);

        // Write to client mirror
        string clientPath = Path.Combine(Application.dataPath, ClientDir, GeneratedFile);
        WriteFile(clientPath, code);

        AssetDatabase.Refresh();
        Debug.Log($"[GameplayTagCodeGenerator] Generated {asset.Tags.Count} tags → {serverPath}");
    }

    private static GameplayTagConfigAsset FindConfigAsset()
    {
        var guids = AssetDatabase.FindAssets("t:GameplayTagConfigAsset");
        if (guids.Length == 0) return null;
        string path = AssetDatabase.GUIDToAssetPath(guids[0]);
        return AssetDatabase.LoadAssetAtPath<GameplayTagConfigAsset>(path);
    }

    private static string GenerateCode(List<GameplayTagConfigAsset.TagDef> tags)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by GameplayTagCodeGenerator from GameplayTagConfigAsset.");
        sb.AppendLine("// Usage: Copy the tag registration block into GameplayTagConfig.Initialize().");
        sb.AppendLine();
        sb.AppendLine("namespace ShootingGame.Shared.GameplayTags");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");

        foreach (var tag in tags)
        {
            string fieldName = tag.Name.Replace(".", "_");
            string parentArg = string.IsNullOrEmpty(tag.Parent) ? "null" : $"\"{tag.Parent}\"";
            sb.AppendLine($"    /// Id_{fieldName} = GameplayTagManager.Register(\"{tag.Name}\", {parentArg});");
        }

        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class GameplayTagConfigGenerated");
        sb.AppendLine("    {");
        sb.AppendLine("        public static void RegisterAllTags()");
        sb.AppendLine("        {");
        sb.AppendLine("            GameplayTagManager.Reset();");
        sb.AppendLine();

        foreach (var tag in tags)
        {
            string fieldName = tag.Name.Replace(".", "_");
            string parentArg = string.IsNullOrEmpty(tag.Parent) ? "null" : $"\"{tag.Parent}\"";
            sb.AppendLine($"            GameplayTagConfig.Id_{fieldName} = GameplayTagManager.Register(\"{tag.Name}\", {parentArg});");
        }

        sb.AppendLine();
        sb.AppendLine("            GameplayTagManager.Bake();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void WriteFile(string path, string content)
    {
        var dir = Path.GetDirectoryName(path);
        if (!Directory.Exists(dir))
            Directory.CreateDirectory(dir);
        File.WriteAllText(path, content, Encoding.UTF8);
    }

    private static void OnPostprocessAllAssets(string[] imported, string[] deleted, string[] moved, string[] movedFrom)
    {
        foreach (string path in imported)
        {
            if (path.Contains("GameplayTagConfig") && path.EndsWith(".asset"))
            {
                Generate();
                return;
            }
        }
    }
}
