using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ShootingGame.SourceGen
{
    /// <summary>
    /// Source Generator for [ServerRpc] and [ClientRpc] methods on NetworkBehaviour subclasses.
    ///
    /// For each RPC method, generates:
    /// - A client-side proxy that serializes args and sends via SendServerRpc
    /// - A server-side dispatch handler that deserializes args and invokes the method
    /// - Registration code in the static constructor
    /// </summary>
    [Generator]
    public class RpcMethodGenerator : ISourceGenerator
    {
        private const string ServerRpcAttrName = "ServerRpcAttribute";
        private const string ClientRpcAttrName = "ClientRpcAttribute";
        private const string NetworkBehaviourName = "NetworkBehaviour";

        // Supported RPC parameter types (same as SyncVar types)
        private static readonly Dictionary<string, (string write, string read)> _typeMap =
            new Dictionary<string, (string, string)>
            {
                { "byte",   ("w.WriteByte(value)",   "r.ReadByte()") },
                { "int",    ("w.WriteInt32(value)",  "r.ReadInt32()") },
                { "uint",   ("w.WriteUInt32(value)", "r.ReadUInt32()") },
                { "float",  ("w.WriteFloat(value)",  "r.ReadFloat()") },
                { "bool",   ("w.WriteBool(value)",   "r.ReadBool()") },
                { "long",   ("w.WriteInt64(value)",  "r.ReadInt64()") },
                { "Vec2",   ("w.WriteVec2(value)",   "r.ReadVec2()") },
                { "Vec3",   ("w.WriteVec3(value)",   "r.ReadVec3()") },
                { "Quat",   ("w.WriteQuat(value)",   "r.ReadQuat()") },
            };

        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new RpcMethodReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not RpcMethodReceiver receiver)
                return;

            // Group RPC methods by their containing class
            var rpcClasses = new Dictionary<INamedTypeSymbol, List<(IMethodSymbol method, bool isServerRpc, bool isClientRpc)>>(SymbolEqualityComparer.Default);

            foreach (var methodDecl in receiver.CandidateMethods)
            {
                var model = context.Compilation.GetSemanticModel(methodDecl.SyntaxTree);
                if (model.GetDeclaredSymbol(methodDecl) is not IMethodSymbol methodSymbol)
                    continue;

                var containingType = methodSymbol.ContainingType;
                if (containingType == null) continue;

                // Check if containing type inherits from NetworkBehaviour
                if (!IsNetworkBehaviour(containingType))
                    continue;

                bool isServerRpc = HasAttribute(methodSymbol, ServerRpcAttrName);
                bool isClientRpc = HasAttribute(methodSymbol, ClientRpcAttrName);

                if (!isServerRpc && !isClientRpc) continue;

                if (!rpcClasses.TryGetValue(containingType, out var methods))
                {
                    methods = new List<(IMethodSymbol, bool, bool)>();
                    rpcClasses[containingType] = methods;
                }
                methods.Add((methodSymbol, isServerRpc, isClientRpc));
            }

            // Generate code for each class with RPC methods
            foreach (var kvp in rpcClasses)
            {
                var classSymbol = kvp.Key;
                var rpcMethods = kvp.Value;
                var source = GenerateRpcCode(classSymbol, rpcMethods);
                if (source != null)
                {
                    var hintName = $"{classSymbol.ContainingNamespace}_{classSymbol.Name}_Rpc.g.cs";
                    context.AddSource(hintName, source);
                }
            }
        }

        private static string? GenerateRpcCode(
            INamedTypeSymbol classSymbol,
            List<(IMethodSymbol method, bool isServerRpc, bool isClientRpc)> rpcMethods)
        {
            var namespaceName = classSymbol.ContainingNamespace?.ToDisplayString() ?? "Global";
            var className = classSymbol.Name;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using ShootingGame.Network;");
            sb.AppendLine("using ShootingGame.Shared.Protocol;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    partial class {className}");
            sb.AppendLine("    {");

            // Static constructor to register RPC handlers
            sb.AppendLine("        static " + className + "()");
            sb.AppendLine("        {");

            foreach (var (method, isServerRpc, _) in rpcMethods)
            {
                long methodHash = ComputeMethodHash(method);
                string handlerName = $"__RpcHandler_{method.Name}_{methodHash:X}";

                sb.AppendLine($"            RpcMethodRegistry.Register(0x{methodHash:X}L, {handlerName});");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // Generate proxy methods for ServerRpc (client → server)
            foreach (var (method, isServerRpc, _) in rpcMethods)
            {
                if (!isServerRpc) continue;

                var paramList = string.Join(", ", method.Parameters.Select(p => $"{p.Type.Name} {p.Name}"));
                var argList = string.Join(", ", method.Parameters.Select(p => p.Name));

                sb.AppendLine($"        // ServerRpc proxy (client calls this to send to server, server executes the {method.Name} body)");
                sb.AppendLine($"        public void InvokeServerRpc_{method.Name}({paramList})");
                sb.AppendLine("        {");
                sb.AppendLine("            // Serialize args");
                sb.AppendLine("            var w = new PacketWriter();");
                sb.AppendLine($"            w.WriteUInt32(NetId);");
                sb.AppendLine($"            w.WriteInt64(0x{ComputeMethodHash(method):X}L);");
                sb.AppendLine($"            w.WriteUInt32(0); // reqId");

                foreach (var param in method.Parameters)
                {
                    var typeName = param.Type.Name;
                    if (_typeMap.TryGetValue(typeName, out var methods))
                    {
                        sb.AppendLine($"            {{ var value = {param.Name}; {methods.write.Replace("value", param.Name)}; }}");
                    }
                    else
                    {
                        // Unknown type - skip (report diagnostic ideally)
                        sb.AppendLine($"            // WARNING: unsupported type '{typeName}' for parameter '{param.Name}'");
                    }
                }

                sb.AppendLine("            var payload = w.ToArray();");
                sb.AppendLine("            SendServerRpc(payload);");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            // Generate dispatch handlers
            foreach (var (method, isServerRpc, _) in rpcMethods)
            {
                if (!isServerRpc) continue;

                long methodHash = ComputeMethodHash(method);
                string handlerName = $"__RpcHandler_{method.Name}_{methodHash:X}";

                sb.AppendLine($"        private static void {handlerName}(ShootingGame.Network.NetworkBehaviour target, PacketReader r)");
                sb.AppendLine("        {");
                sb.AppendLine($"            var self = ({className})target;");

                // Deserialize args
                var readStatements = new List<string>();
                foreach (var param in method.Parameters)
                {
                    var typeName = param.Type.Name;
                    if (_typeMap.TryGetValue(typeName, out var methods))
                    {
                        readStatements.Add($"var {param.Name} = {methods.read};");
                    }
                }

                // Build arg list for call
                var callArgs = string.Join(", ", method.Parameters.Select(p => p.Name));

                sb.AppendLine($"            // Deserialize args");
                foreach (var stmt in readStatements)
                    sb.AppendLine($"            {stmt}");
                sb.AppendLine();
                sb.AppendLine($"            // Invoke");
                sb.AppendLine($"            self.{method.Name}({callArgs});");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        // ==================== Helpers ====================

        private static long ComputeMethodHash(IMethodSymbol method)
        {
            // Build a deterministic string: FullTypeName.MethodName(ParamType1,ParamType2)
            var sb = new StringBuilder();
            sb.Append(method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            sb.Append('.');
            sb.Append(method.Name);
            sb.Append('(');
            for (int i = 0; i < method.Parameters.Length; i++)
            {
                if (i > 0) sb.Append(',');
                sb.Append(method.Parameters[i].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            }
            sb.Append(')');

            using var sha = SHA256.Create();
            var bytes = sha.ComputeHash(Encoding.UTF8.GetBytes(sb.ToString()));
            return BitConverter.ToInt64(bytes, 0);
        }

        private static bool IsNetworkBehaviour(INamedTypeSymbol type)
        {
            var current = type;
            while (current != null)
            {
                if (current.Name == NetworkBehaviourName)
                    return true;
                current = current.BaseType;
            }
            return false;
        }

        private static bool HasAttribute(ISymbol symbol, string attrName)
        {
            return symbol.GetAttributes()
                .Any(a => a.AttributeClass?.Name == attrName ||
                          a.AttributeClass?.Name == attrName.Replace("Attribute", ""));
        }

        /// <summary>
        /// Syntax receiver: collects all method declarations with attributes.
        /// </summary>
        private class RpcMethodReceiver : ISyntaxReceiver
        {
            public readonly List<MethodDeclarationSyntax> CandidateMethods = new List<MethodDeclarationSyntax>();

            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
                if (syntaxNode is MethodDeclarationSyntax methodDecl &&
                    methodDecl.AttributeLists.Count > 0)
                {
                    CandidateMethods.Add(methodDecl);
                }
            }
        }
    }
}
