using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ShootingGame.SourceGen
{
    /// <summary>
    /// Enhanced Source Generator for [ServerRpc] and [ClientRpc] methods.
    ///
    /// 参考 SpaceBuilder RPC 系统增强版：
    ///   - [ServerRpc] void → Fire-and-Forget 代理
    ///   - [ServerRpc] Task&lt;T&gt; → 异步 Request/Response 代理（集成 RpcTransactionService）
    ///   - [ClientRpc] void → 服务端广播代理 + 客户端分发处理
    ///   - [ClientRpc] Task&lt;T&gt; → 服务端 Request/Response 代理
    ///
    /// 生成文件命名: {Namespace}_{ClassName}_Rpc.g.cs
    /// </summary>
    [Generator]
    public class RpcMethodGenerator : ISourceGenerator
    {
        private const string ServerRpcAttrName = "ServerRpcAttribute";
        private const string ClientRpcAttrName = "ClientRpcAttribute";
        private const string NetworkBehaviourName = "NetworkBehaviour";

        // Supported RPC parameter types
        private static readonly Dictionary<string, (string write, string read)> _typeMap =
            new Dictionary<string, (string, string)>
            {
                { "byte",   ("w.WriteByte(value)",   "r.ReadByte()") },
                { "int",    ("w.WriteInt32(value)",  "r.ReadInt32()") },
                { "uint",   ("w.WriteUInt32(value)", "r.ReadUInt32()") },
                { "float",  ("w.WriteFloat(value)",  "r.ReadFloat()") },
                { "bool",   ("w.WriteBool(value)",   "r.ReadBool()") },
                { "long",   ("w.WriteInt64(value)",  "r.ReadInt64()") },
                { "Vec2",   ("w.WriteVec2(value)",   "r.ReadVec2()") },
                { "Vec3",   ("w.WriteVec3(value)",   "r.ReadVec3()") },
                { "Quat",   ("w.WriteQuat(value)",   "r.ReadQuat()") },
                { "string", ("w.WriteString(value)", "r.ReadString()") },
            };

        // Return type names that indicate async
        private static readonly HashSet<string> _asyncReturnTypes = new HashSet<string>
        {
            "Task", "Task`1", "UniTask", "UniTask`1", "ValueTask", "ValueTask`1"
        };

        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new RpcMethodReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not RpcMethodReceiver receiver)
                return;

            var rpcClasses = new Dictionary<INamedTypeSymbol, List<(IMethodSymbol method, bool isServerRpc, bool isClientRpc)>>(SymbolEqualityComparer.Default);

            foreach (var methodDecl in receiver.CandidateMethods)
            {
                var model = context.Compilation.GetSemanticModel(methodDecl.SyntaxTree);
                if (model.GetDeclaredSymbol(methodDecl) is not IMethodSymbol methodSymbol)
                    continue;

                var containingType = methodSymbol.ContainingType;
                if (containingType == null) continue;

                if (!IsNetworkBehaviour(containingType))
                    continue;

                bool isServerRpc = HasAttribute(methodSymbol, ServerRpcAttrName);
                bool isClientRpc = HasAttribute(methodSymbol, ClientRpcAttrName);

                if (!isServerRpc && !isClientRpc) continue;

                if (!rpcClasses.TryGetValue(containingType, out var methods))
                {
                    methods = new List<(IMethodSymbol, bool, bool)>();
                    rpcClasses[containingType] = methods;
                }
                methods.Add((methodSymbol, isServerRpc, isClientRpc));
            }

            foreach (var kvp in rpcClasses)
            {
                var classSymbol = kvp.Key;
                var rpcMethods = kvp.Value;
                var source = GenerateRpcCode(classSymbol, rpcMethods);
                if (source != null)
                {
                    var hintName = $"{classSymbol.ContainingNamespace}_{classSymbol.Name}_Rpc.g.cs";
                    context.AddSource(hintName, source);
                }
            }
        }

        private static string? GenerateRpcCode(
            INamedTypeSymbol classSymbol,
            List<(IMethodSymbol method, bool isServerRpc, bool isClientRpc)> rpcMethods)
        {
            var namespaceName = classSymbol.ContainingNamespace?.ToDisplayString() ?? "Global";
            var className = classSymbol.Name;
            var fullTypeName = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// 由 RpcMethodGenerator 生成（参考 SpaceBuilder RPC 系统）");
            sb.AppendLine("// [ServerRpc] / [ClientRpc] → Roslyn 编译时生成代理和分发代码");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using ShootingGame.Network;");
            sb.AppendLine("using ShootingGame.Shared.Protocol;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    partial class {className}");
            sb.AppendLine("    {");

            // ========== 静态构造：注册所有 RPC 处理器 ==========
            sb.AppendLine("        static " + className + "()");
            sb.AppendLine("        {");

            foreach (var (method, isServerRpc, isClientRpc) in rpcMethods)
            {
                long methodHash = ComputeMethodHash(method);
                string handlerName = $"__RpcHandler_{method.Name}_{methodHash:X}";
                sb.AppendLine($"            RpcMethodRegistry.Register(0x{methodHash:X}L, {handlerName});");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // ========== Generate proxies and handlers ==========
            foreach (var (method, isServerRpc, isClientRpc) in rpcMethods)
            {
                long methodHash = ComputeMethodHash(method);
                bool isAsync = IsAsyncMethod(method);

                if (isServerRpc)
                {
                    if (isAsync)
                        GenerateAsyncServerRpcProxy(sb, method, methodHash, className);
                    else
                        GenerateFireAndForgetServerRpcProxy(sb, method, methodHash, className);

                    GenerateDispatchHandler(sb, method, methodHash, className);
                }

                if (isClientRpc)
                {
                    if (isAsync)
                        GenerateAsyncClientRpcProxy(sb, method, methodHash, className);
                    else
                        GenerateFireAndForgetClientRpcProxy(sb, method, methodHash, className);

                    GenerateClientDispatchHandler(sb, method, methodHash, className);
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // ========== ServerRpc Fire-and-Forget (void) ==========

        private static void GenerateFireAndForgetServerRpcProxy(
            StringBuilder sb, IMethodSymbol method, long methodHash, string className)
        {
            var paramList = BuildParamList(method);
            sb.AppendLine($"        /// <summary>[ServerRpc] 客户端→服务端 (Fire-and-Forget)</summary>");
            sb.AppendLine($"        public void InvokeServerRpc_{method.Name}({paramList})");
            sb.AppendLine("        {");
            sb.AppendLine("            var w = new PacketWriter();");
            sb.AppendLine($"            w.WriteUInt32(NetId);");
            sb.AppendLine($"            w.WriteInt64(0x{methodHash:X}L);");
            sb.AppendLine("            w.WriteUInt32(0); // reqId=0 = Fire-and-Forget");
            WriteSerializeParams(sb, method);
            sb.AppendLine("            SendServerRpc(w.ToArray());");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ========== ServerRpc Async (Task<T>) — 使用 RpcTransactionService ==========

        private static void GenerateAsyncServerRpcProxy(
            StringBuilder sb, IMethodSymbol method, long methodHash, string className)
        {
            var returnType = GetAsyncReturnType(method);
            var paramList = BuildParamList(method);
            var callArgs = string.Join(", ", method.Parameters.Select(p => p.Name));

            sb.AppendLine($"        /// <summary>[ServerRpc] 客户端→服务端 (异步 Request/Response)</summary>");
            sb.AppendLine($"        public async Task<{returnType}> InvokeServerRpc_{method.Name}({paramList})");
            sb.AppendLine("        {");
            sb.AppendLine("            var w = new PacketWriter();");
            WriteSerializeParams(sb, method);
            sb.AppendLine("            var payload = w.ToArray();");
            sb.AppendLine($"            var result = await RpcTransactionService.Instance.SendServerRequestAsync(");
            sb.AppendLine($"                NetId, 0x{methodHash:X}L, payload);");
            sb.AppendLine($"            // 反序列化返回值");
            sb.AppendLine($"            var r = new PacketReader(result);");
            if (returnType == "byte")       sb.AppendLine("            return r.ReadByte();");
            else if (returnType == "int")   sb.AppendLine("            return r.ReadInt32();");
            else if (returnType == "float") sb.AppendLine("            return r.ReadFloat();");
            else if (returnType == "bool")  sb.AppendLine("            return r.ReadBool();");
            else if (returnType == "long")  sb.AppendLine("            return r.ReadInt64();");
            else if (returnType == "string") sb.AppendLine("            return r.ReadString();");
            else if (returnType == "Vec2")  sb.AppendLine("            return r.ReadVec2();");
            else if (returnType == "Vec3")  sb.AppendLine("            return r.ReadVec3();");
            else if (returnType == "Quat")  sb.AppendLine("            return r.ReadQuat();");
            else sb.AppendLine($"            return default({returnType}); // WARNING: unsupported return type");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ========== ServerRpc Dispatch Handler (on server) ==========

        private static void GenerateDispatchHandler(
            StringBuilder sb, IMethodSymbol method, long methodHash, string className)
        {
            bool isAsync = IsAsyncMethod(method);
            string handlerName = $"__RpcHandler_{method.Name}_{methodHash:X}";

            sb.AppendLine($"        private static void {handlerName}(ShootingGame.Network.NetworkBehaviour target, PacketReader r)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var self = ({className})target;");

            // Deserialize args
            foreach (var param in method.Parameters)
            {
                var typeName = param.Type.Name;
                if (_typeMap.TryGetValue(typeName, out var methods))
                    sb.AppendLine($"            var {param.Name} = {methods.read};");
                else
                    sb.AppendLine($"            // WARNING: unsupported type '{typeName}' — var {param.Name} = default;");
            }

            var callArgs = string.Join(", ", method.Parameters.Select(p => p.Name));

            if (isAsync)
            {
                // 异步方法：执行后发回 RpcResponseMsg
                sb.AppendLine($"            var __result = await self.{method.Name}({callArgs});");
                sb.AppendLine($"            var __respW = new PacketWriter();");
                WriteSerializeReturnValue(sb, method, "__result");
                sb.AppendLine($"            var __respPayload = __respW.ToArray();");
                sb.AppendLine($"            // TODO: 通过 r.ReadUInt32() 获取 reqId 并发回 RpcResponseMsg");
                sb.AppendLine($"            // RpcTransactionService.Instance.SendResponse(reqId, __respPayload);");
            }
            else
            {
                sb.AppendLine($"            self.{method.Name}({callArgs});");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ========== ClientRpc Fire-and-Forget (void) ==========

        private static void GenerateFireAndForgetClientRpcProxy(
            StringBuilder sb, IMethodSymbol method, long methodHash, string className)
        {
            var paramList = BuildParamList(method);
            sb.AppendLine($"        /// <summary>[ClientRpc] 服务端→客户端 (Fire-and-Forget)</summary>");
            sb.AppendLine($"        public void InvokeClientRpc_{method.Name}({paramList}, ClientRpcTarget target = ClientRpcTarget.All)");
            sb.AppendLine("        {");
            sb.AppendLine("            var w = new PacketWriter();");
            sb.AppendLine($"            w.WriteUInt32(NetId);");
            sb.AppendLine($"            w.WriteInt64(0x{methodHash:X}L);");
            sb.AppendLine("            w.WriteUInt32(0); // reqId=0");
            WriteSerializeParams(sb, method);
            sb.AppendLine("            SendClientRpc(w.ToArray(), target);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ========== ClientRpc Async (Task<T>) ==========

        private static void GenerateAsyncClientRpcProxy(
            StringBuilder sb, IMethodSymbol method, long methodHash, string className)
        {
            var returnType = GetAsyncReturnType(method);
            var paramList = BuildParamList(method);

            sb.AppendLine($"        /// <summary>[ClientRpc] 服务端→指定客户端 (异步 Request/Response)</summary>");
            sb.AppendLine($"        public async Task<{returnType}> InvokeClientRpc_{method.Name}({paramList}, int targetPlayerId)");
            sb.AppendLine("        {");
            sb.AppendLine("            var w = new PacketWriter();");
            WriteSerializeParams(sb, method);
            sb.AppendLine("            var payload = w.ToArray();");
            sb.AppendLine($"            var result = await RpcTransactionService.Instance.SendClientRequestAsync(");
            sb.AppendLine($"                NetId, 0x{methodHash:X}L, payload, targetPlayerId);");
            sb.AppendLine($"            var r = new PacketReader(result);");
            if (returnType == "byte")       sb.AppendLine("            return r.ReadByte();");
            else if (returnType == "int")   sb.AppendLine("            return r.ReadInt32();");
            else if (returnType == "float") sb.AppendLine("            return r.ReadFloat();");
            else if (returnType == "bool")  sb.AppendLine("            return r.ReadBool();");
            else sb.AppendLine($"            return default({returnType});");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ========== ClientRpc Dispatch Handler (on client) ==========

        private static void GenerateClientDispatchHandler(
            StringBuilder sb, IMethodSymbol method, long methodHash, string className)
        {
            bool isAsync = IsAsyncMethod(method);
            string handlerName = $"__RpcClientHandler_{method.Name}_{methodHash:X}";

            sb.AppendLine($"        private static void {handlerName}(ShootingGame.Network.NetworkBehaviour target, PacketReader r)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var self = ({className})target;");

            foreach (var param in method.Parameters)
            {
                var typeName = param.Type.Name;
                if (_typeMap.TryGetValue(typeName, out var methods))
                    sb.AppendLine($"            var {param.Name} = {methods.read};");
                else
                    sb.AppendLine($"            // WARNING: unsupported type '{typeName}'");
            }

            var callArgs = string.Join(", ", method.Parameters.Select(p => p.Name));

            if (isAsync)
            {
                sb.AppendLine($"            var __result = await self.{method.Name}({callArgs});");
                sb.AppendLine($"            // TODO: reply with RpcResponseMsg");
            }
            else
            {
                sb.AppendLine($"            self.{method.Name}({callArgs});");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ========== Serialization Helpers ==========

        private static void WriteSerializeParams(StringBuilder sb, IMethodSymbol method)
        {
            foreach (var param in method.Parameters)
            {
                var typeName = param.Type.Name;
                if (_typeMap.TryGetValue(typeName, out var methods))
                    sb.AppendLine($"            {{ var value = {param.Name}; {methods.write.Replace("value", param.Name)}; }}");
                else
                    sb.AppendLine($"            // WARNING: unsupported type '{typeName}'");
            }
        }

        private static void WriteSerializeReturnValue(StringBuilder sb, IMethodSymbol method, string varName)
        {
            var returnType = GetAsyncReturnType(method);
            if (_typeMap.TryGetValue(returnType, out var methods))
                sb.AppendLine($"            {{ var value = {varName}; {methods.write.Replace("value", varName)}; }}");
            else
                sb.AppendLine($"            // WARNING: unsupported return type '{returnType}'");
        }

        // ========== Type Analysis ==========

        private static bool IsAsyncMethod(IMethodSymbol method)
        {
            var returnType = method.ReturnType;
            if (returnType is INamedTypeSymbol namedType)
            {
                var typeName = namedType.Name;
                if (_asyncReturnTypes.Contains(typeName))
                    return true;
                if (namedType.IsGenericType)
                {
                    var genericDef = namedType.ConstructedFrom?.Name ?? namedType.Name;
                    if (_asyncReturnTypes.Contains(genericDef))
                        return true;
                }
            }
            return false;
        }

        private static string GetAsyncReturnType(IMethodSymbol method)
        {
            var returnType = method.ReturnType;
            if (returnType is INamedTypeSymbol namedType && namedType.IsGenericType)
            {
                var typeArg = namedType.TypeArguments.FirstOrDefault();
                if (typeArg != null)
                    return typeArg.Name;
            }
            return "byte"; // default
        }

        private static string BuildParamList(IMethodSymbol method)
        {
            return string.Join(", ", method.Parameters.Select(p => $"{p.Type.Name} {p.Name}"));
        }

        // ========== Infrastructure ==========

        private static long ComputeMethodHash(IMethodSymbol method)
        {
            var sb = new StringBuilder();
            sb.Append(method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            sb.Append('.');
            sb.Append(method.Name);
            sb.Append('(');
            for (int i = 0; i < method.Parameters.Length; i++)
            {
                if (i > 0) sb.Append(',');
                sb.Append(method.Parameters[i].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            }
            sb.Append(')');

            using var sha = SHA256.Create();
            var bytes = sha.ComputeHash(Encoding.UTF8.GetBytes(sb.ToString()));
            return BitConverter.ToInt64(bytes, 0);
        }

        private static bool IsNetworkBehaviour(INamedTypeSymbol type)
        {
            var current = type;
            while (current != null)
            {
                if (current.Name == NetworkBehaviourName)
                    return true;
                current = current.BaseType;
            }
            return false;
        }

        private static bool HasAttribute(ISymbol symbol, string attrName)
        {
            return symbol.GetAttributes()
                .Any(a => a.AttributeClass?.Name == attrName ||
                          a.AttributeClass?.Name == attrName.Replace("Attribute", ""));
        }

        // ========== Syntax Receiver ==========

        private class RpcMethodReceiver : ISyntaxReceiver
        {
            public readonly List<MethodDeclarationSyntax> CandidateMethods = new List<MethodDeclarationSyntax>();

            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
                if (syntaxNode is MethodDeclarationSyntax methodDecl &&
                    methodDecl.AttributeLists.Count > 0)
                {
                    CandidateMethods.Add(methodDecl);
                }
            }
        }
    }
}
